### ISSUE TITLE
download file timeout when installing chocolatey

### ISSUE THREAD

**Issue by mxj4** [chocolatey/chocolatey#438]
Hi,
I got timeout error when executing `https://chocolatey.org/install.ps1`
when it comes to download 7za from github.

I'm installing chocolatey in Packer provisioner so there are more output, but running install command in windows cmd result in same error. I can download the file directly so not a network problem.
System is Windows 7 Professional with SP1 x64

```
    virtualbox-iso: Mode                LastWriteTime     Length Name
    virtualbox-iso: ----                -------------     ------ ----
    virtualbox-iso: d----         3/20/2014  12:49 AM            chocInstall
    virtualbox-iso: Downloading http://chocolatey.org/api/v2/package/chocolatey/ to C:\Windows\Temp\chocolatey\chocInstall\chocolatey.zip
    virtualbox-iso: Download 7Zip commandline tool
    virtualbox-iso: Downloading https://github.com/chocolatey/chocolatey/blob/master/src/tools/7za.exe?raw=true to C:\Windows\Temp\chocolatey\chocInstall\7za.exe
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "The operation has timed
    virtualbox-iso: out"
    virtualbox-iso: At line:33 char:27
    virtualbox-iso: +   $downloader.DownloadFile <<<< ($url, $file)
    virtualbox-iso: + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso: + FullyQualifiedErrorId : DotNetMethodException
    virtualbox-iso:
    virtualbox-iso: Extracting C:\Windows\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Windows\Temp\chocolatey\chocInstall...
    virtualbox-iso: Start-Process : This command cannot be executed due to the error: The system ca
    virtualbox-iso: nnot find the file specified.
    virtualbox-iso: At line:47 char:14
    virtualbox-iso: + Start-Process <<<<  "$7zaExe" -ArgumentList "x -o`"$tempDir`" -y `"$file`"" -
    virtualbox-iso: Wait
    virtualbox-iso: + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp
    virtualbox-iso: erationException
    virtualbox-iso: + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C
    virtualbox-iso: ommands.StartProcessCommand
    virtualbox-iso:
    virtualbox-iso: Installing chocolatey on this machine
    virtualbox-iso: The term 'C:\Windows\Temp\chocolatey\chocInstall\tools\chocolateyInstall.ps1' i
    virtualbox-iso: s not recognized as the name of a cmdlet, function, script file, or operable pr
    virtualbox-iso: ogram. Check the spelling of the name, or if a path was included, verify that t
    virtualbox-iso: he path is correct and try again.
    virtualbox-iso: At line:58 char:2
    virtualbox-iso: + & <<<<  $chocInstallPS1
    virtualbox-iso: + CategoryInfo          : ObjectNotFound: (C:\Windows\Temp...ateyInstall.p
    virtualbox-iso: s1:String) [], CommandNotFoundException
    virtualbox-iso: + FullyQualifiedErrorId : CommandNotFoundException
```
